import{a as E,S,i}from"./assets/vendor-KnZd4sWe.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const w="49140173-4874def0c004e38bcbb22fb6b",L="https://pixabay.com/api/";async function f(e,r=1){const a=`${L}?key=${w}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=40&page=${r}`;try{const s=await E.get(a);return s.data.hits.length===0?Promise.reject(new Error("No images found.")):{images:s.data.hits,totalHits:s.data.totalHits}}catch{throw new Error("Failed to fetch images.")}}const y=document.querySelector(".gallery");let $=new S(".gallery a");function g(e){const r=e.map(({webformatURL:a,largeImageURL:s,tags:t,likes:o,views:n,comments:h,downloads:b})=>`
      <a href="${s}" class="gallery-item">
        <img src="${a}" alt="${t}" />
        <div class="info">
          <p>❤️ ${o}</p>
          <p>👀 ${n}</p>
          <p>💬 ${h}</p>
          <p>⬇️ ${b}</p>
        </div>
      </a>`).join("");y.insertAdjacentHTML("beforeend",r),$.refresh()}function q(){y.innerHTML=""}const m=document.querySelector("#search-form"),u=document.querySelector(".loader");document.querySelector(".gallery");const d=document.querySelector("#load-more");let c="",l=1;const p=40;m.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.target.elements.searchQuery.value.trim(),!c){i.error({title:"Error",message:"Please enter a search query!"});return}q(),l=1,u.style.display="block",d.style.display="none";try{const{images:r,totalHits:a}=await f(c,l);r.length>0?(g(r),i.success({title:"Success",message:"Images loaded!"}),a>p&&(d.style.display="block")):i.error({title:"Error",message:"No images found."})}catch(r){i.error({title:"Error",message:r.message})}finally{u.style.display="none",m.reset()}});d.addEventListener("click",async()=>{l+=1,u.style.display="block";try{const{images:e,totalHits:r}=await f(c,l);e.length>0&&(g(e),v()),l*p>=r&&(d.style.display="none",i.info({title:"Info",message:"No more images to load."}))}catch(e){i.error({title:"Error",message:e.message})}finally{u.style.display="none"}});function v(){const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}function I(e){i.success({title:"Hi!",message:e,position:"topRight",timeout:3e3,transitionIn:"fadeInUp",transitionOut:"fadeOutDown",close:!1})}I("Welcome to the cutest gallery ever! 💖");
//# sourceMappingURL=index.js.map
